apiVersion: v1
kind: Pod
metadata:
 name: azure-files-pod
spec:
 containers:
  - image: kubernetes/pause
    name: azure-files
    volumeMounts:
      - name: azure-files
        mountPath: /mnt/azure
 nodeSelector:
    beta.kubernetes.io/os: linux
 volumes:
  - name: azure
    azureFile:
      secretName: azure-secret
      shareName: k8sshare
      readOnly: false